# Generated by Django 5.1.4 on 2025-01-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="type",
            new_name="type_field",
        ),
    ]
