# Generated by Django 5.1.4 on 2025-01-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_user_alter_payment_borrowing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
    ]
